#!/bin/bash
#filename watchdir.sh
path=$1
/usr/bin/inotifywait -mrq --timefmt '%d/%m/%y/%H:%M' --format '%T %w %f' -e modify,delete,create,attrib $path

执行输出：
./watchdir.sh /data/wsdata/tools/

 inotifywait命令参数

    -m是要持续监视变化。
    -r使用递归形式监视目录。
    -q减少冗余信息，只打印出需要的信息。
    -e指定要监视的事件列表。
    --timefmt是指定时间的输出格式。
    --format指定文件变化的详细信息。

可监听的事件
事件 	                         描述
access 	               访问，读取文件。
modify 	               修改，文件内容被修改。
attrib 	               属性，文件元数据被修改。
move 	               移动，对文件进行移动操作。
create 	               创建，生成新文件
open 	               打开，对文件进行打开操作。
close 	               关闭，对文件进行关闭操作。
delete 	               删除，文件被删除。 